# Generated by Django 6.0.2 on 2026-06-03 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Station météo',
            },
        ),
        migrations.CreateModel(
            name='DonneesMensuelles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('mois', models.IntegerField()),
                ('temperature_moy', models.FloatField(help_text='Température moyenne mensuelle (°C)')),
                ('precipitation', models.FloatField(help_text='Précipitations totales mensuelles (mm)')),
                ('humidite_moy', models.FloatField(blank=True, help_text='Humidité relative moyenne (%)', null=True)),
                ('insolation', models.FloatField(blank=True, help_text='Insolation totale (Wh/m²)', null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donnees', to='bilan_hydro.station')),
            ],
            options={
                'ordering': ['annee', 'mois'],
                'unique_together': {('station', 'annee', 'mois')},
            },
        ),
        migrations.CreateModel(
            name='BilanHydro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('methode', models.CharField(choices=[('thornthwaite', 'Thornthwaite'), ('turc', 'Turc')], max_length=20)),
                ('annee', models.IntegerField()),
                ('mois', models.IntegerField()),
                ('etp', models.FloatField(help_text='Évapotranspiration potentielle (mm)')),
                ('etr', models.FloatField(help_text='Évapotranspiration réelle (mm)')),
                ('rfu', models.FloatField(help_text='Réserve Facilement Utilisable (mm)')),
                ('da', models.FloatField(help_text='Déficit Agricole (mm)')),
                ('variation_stock', models.FloatField(help_text='Variation de stockage (mm)')),
                ('excedent', models.FloatField(default=0, help_text='Excédent / Ruissellement (mm)')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilans', to='bilan_hydro.station')),
            ],
            options={
                'ordering': ['annee', 'mois'],
                'unique_together': {('station', 'methode', 'annee', 'mois')},
            },
        ),
    ]
