from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True
    dependencies = []

    operations = [

        # ── Station ──────────────────────────────────────────────────────────
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('identification', models.CharField(max_length=5, unique=True,
                    verbose_name='Indicatif mécanographique')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la station')),
                ('type_station', models.CharField(max_length=1, default='2',
                    choices=[('1','Synoptique'),('2','Agro-météo'),('3','Climatologique principale'),
                             ('4','Climatologique ordinaire'),('5','Poste pluviométrique'),
                             ('6','Pluvio + agro'),('9','Indéterminé')],
                    verbose_name='Type de station')),
                ('longitude', models.FloatField(verbose_name='Longitude (°E)')),
                ('latitude',  models.FloatField(verbose_name='Latitude (°S)')),
                ('altitude',  models.FloatField(null=True, blank=True, verbose_name='Altitude (m)')),
            ],
            options={'verbose_name':'Station','verbose_name_plural':'Stations','ordering':['nom']},
        ),

        # ── Message ───────────────────────────────────────────────────────────
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('station', models.ForeignKey('Station',
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='messages', null=True, blank=True)),
                ('identification', models.CharField(max_length=5)),
                ('nom',  models.CharField(max_length=100, blank=True)),
                ('longitude', models.FloatField(null=True, blank=True)),
                ('latitude',  models.FloatField(null=True, blank=True)),
                ('altitude',  models.FloatField(null=True, blank=True)),
                ('annee',  models.IntegerField(verbose_name='Année')),
                ('mois',   models.CharField(max_length=2,
                    choices=[('01','Janvier'),('02','Février'),('03','Mars'),('04','Avril'),
                             ('05','Mai'),('06','Juin'),('07','Juillet'),('08','Août'),
                             ('09','Septembre'),('10','Octobre'),('11','Novembre'),('12','Décembre')],
                    verbose_name='Mois')),
                ('decade', models.CharField(max_length=2,
                    choices=[('51','1ère décade'),('52','2ème décade'),('53','3ème décade')],
                    verbose_name='Décade')),
                ('message_brut', models.TextField(verbose_name='Message AGMET brut')),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('valide', models.BooleanField(default=False,
                    verbose_name='Validé (aucune erreur)')),
            ],
            options={'verbose_name':'Message AGMET','verbose_name_plural':'Messages AGMET',
                     'ordering':['-annee','-mois','-decade']},
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together={('identification','annee','mois','decade')},
        ),

        # ── DonneesMeteo ──────────────────────────────────────────────────────
        migrations.CreateModel(
            name='DonneesMeteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('message', models.OneToOneField('Message',
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='donnees_meteo', null=True, blank=True)),
                ('identification', models.CharField(max_length=5)),
                ('nom',  models.CharField(max_length=100, blank=True)),
                ('longitude', models.FloatField(null=True, blank=True)),
                ('latitude',  models.FloatField(null=True, blank=True)),
                ('altitude',  models.FloatField(null=True, blank=True)),
                ('annee',  models.IntegerField()),
                ('mois',   models.CharField(max_length=2)),
                ('decade', models.CharField(max_length=2)),
                ('fff',    models.FloatField(null=True, blank=True,
                    verbose_name='Vent moyen total (fff)')),
                ('fdfdfd', models.FloatField(null=True, blank=True,
                    verbose_name='Vent diurne total (fdfdfd)')),
                ('tn', models.FloatField(null=True, blank=True,
                    verbose_name='Tmin moyenne décade (°C)')),
                ('tx', models.FloatField(null=True, blank=True,
                    verbose_name='Tmax moyenne décade (°C)')),
                ('un', models.IntegerField(null=True, blank=True,
                    verbose_name='Humidité relative min moyenne (%)')),
                ('ux', models.IntegerField(null=True, blank=True,
                    verbose_name='Humidité relative max moyenne (%)')),
                ('n',   models.IntegerField(null=True, blank=True,
                    verbose_name='Nombre de jours avec pluie')),
                ('rrr', models.FloatField(null=True, blank=True,
                    verbose_name='Précipitation décadaire (mm)')),
                ('id_insol', models.FloatField(null=True, blank=True,
                    verbose_name='Insolation totale (heures)')),
                ('ev',  models.FloatField(null=True, blank=True,
                    verbose_name='Évaporation totale (mm)')),
                ('tng', models.FloatField(null=True, blank=True,
                    verbose_name='T° sol 10 cm moyenne (°C)')),
                ('erreurs', models.TextField(blank=True, default='',
                    verbose_name='Erreurs détectées')),
            ],
            options={'verbose_name':'Données météo','verbose_name_plural':'Données météo',
                     'ordering':['-annee','-mois','-decade']},
        ),

        # ── DonneesAgro ───────────────────────────────────────────────────────
        migrations.CreateModel(
            name='DonneesAgro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('message', models.OneToOneField('Message',
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='donnees_agro', null=True, blank=True)),
                ('identification', models.CharField(max_length=5)),
                ('nom',  models.CharField(max_length=100, blank=True)),
                ('longitude', models.FloatField(null=True, blank=True)),
                ('latitude',  models.FloatField(null=True, blank=True)),
                ('altitude',  models.FloatField(null=True, blank=True)),
                ('annee',  models.IntegerField()),
                ('mois',   models.CharField(max_length=2)),
                ('decade', models.CharField(max_length=2)),
                ('nom_secva', models.CharField(max_length=100, blank=True,
                    verbose_name='Nom SECVA')),
                # Culture 1 — 11CcCcF / 22E1S1A1
                ('culture1',    models.CharField(max_length=100, blank=True,
                    verbose_name='Culture 1')),
                ('code_cult1',  models.CharField(max_length=2, blank=True,
                    verbose_name='Code culture 1')),
                ('phenologie1', models.CharField(max_length=1, blank=True,
                    choices=[('0','Pas observable'),('1','Semis/plantation'),('2','Levée/germination'),
                             ('3','Tallage/végétatif'),('4','Montaison/épiaison'),('5','Floraison'),
                             ('6','Fructification'),('7','Maturation'),('8','Récolte'),('9','Jachère')],
                    verbose_name='Phénologie C1 (F)')),
                ('ennemis1', models.CharField(max_length=1, blank=True,
                    choices=[('0','Aucun'),('1','Insectes'),('2','Maladies fongiques'),
                             ('3','Maladies virales'),('4','Mauvaises herbes'),('5','Oiseaux'),
                             ('6','Rongeurs'),('7','Sécheresse'),("8","Excès d'eau"),('9','Autre')],
                    verbose_name='Ennemis C1 (E)')),
                ('degat1', models.CharField(max_length=1, blank=True,
                    choices=[('0','Aucun dégât'),('1','Dégâts légers'),('2','Dégâts modérés'),
                             ('3','Dégâts graves'),('4','Perte totale')],
                    verbose_name='Dégâts C1 (S)')),
                ('aspect1', models.CharField(max_length=1, blank=True,
                    choices=[('1','Très bon'),('2','Bon'),('3','Moyen'),
                             ('4','Mauvais'),('5','Très mauvais')],
                    verbose_name='Aspect C1 (A)')),
                # Culture 2 — 33CcCcF / 44E2S2A2
                ('culture2',    models.CharField(max_length=100, blank=True, verbose_name='Culture 2')),
                ('code_cult2',  models.CharField(max_length=2, blank=True)),
                ('phenologie2', models.CharField(max_length=1, blank=True,
                    choices=[('0','Pas observable'),('1','Semis/plantation'),('2','Levée/germination'),
                             ('3','Tallage/végétatif'),('4','Montaison/épiaison'),('5','Floraison'),
                             ('6','Fructification'),('7','Maturation'),('8','Récolte'),('9','Jachère')],
                    verbose_name='Phénologie C2 (F)')),
                ('ennemis2', models.CharField(max_length=1, blank=True,
                    choices=[('0','Aucun'),('1','Insectes'),('2','Maladies fongiques'),
                             ('3','Maladies virales'),('4','Mauvaises herbes'),('5','Oiseaux'),
                             ('6','Rongeurs'),('7','Sécheresse'),("8","Excès d'eau"),('9','Autre')],
                    verbose_name='Ennemis C2 (E)')),
                ('degat2', models.CharField(max_length=1, blank=True,
                    choices=[('0','Aucun dégât'),('1','Dégâts légers'),('2','Dégâts modérés'),
                             ('3','Dégâts graves'),('4','Perte totale')],
                    verbose_name='Dégâts C2 (S)')),
                ('aspect2', models.CharField(max_length=1, blank=True,
                    choices=[('1','Très bon'),('2','Bon'),('3','Moyen'),
                             ('4','Mauvais'),('5','Très mauvais')],
                    verbose_name='Aspect C2 (A)')),
                # Culture 3 — 55CcCcF / 66E3S3A3
                ('culture3',    models.CharField(max_length=100, blank=True, verbose_name='Culture 3')),
                ('code_cult3',  models.CharField(max_length=2, blank=True)),
                ('phenologie3', models.CharField(max_length=1, blank=True,
                    choices=[('0','Pas observable'),('1','Semis/plantation'),('2','Levée/germination'),
                             ('3','Tallage/végétatif'),('4','Montaison/épiaison'),('5','Floraison'),
                             ('6','Fructification'),('7','Maturation'),('8','Récolte'),('9','Jachère')],
                    verbose_name='Phénologie C3 (F)')),
                ('ennemis3', models.CharField(max_length=1, blank=True,
                    choices=[('0','Aucun'),('1','Insectes'),('2','Maladies fongiques'),
                             ('3','Maladies virales'),('4','Mauvaises herbes'),('5','Oiseaux'),
                             ('6','Rongeurs'),('7','Sécheresse'),("8","Excès d'eau"),('9','Autre')],
                    verbose_name='Ennemis C3 (E)')),
                ('degat3', models.CharField(max_length=1, blank=True,
                    choices=[('0','Aucun dégât'),('1','Dégâts légers'),('2','Dégâts modérés'),
                             ('3','Dégâts graves'),('4','Perte totale')],
                    verbose_name='Dégâts C3 (S)')),
                ('aspect3', models.CharField(max_length=1, blank=True,
                    choices=[('1','Très bon'),('2','Bon'),('3','Moyen'),
                             ('4','Mauvais'),('5','Très mauvais')],
                    verbose_name='Aspect C3 (A)')),
            ],
            options={'verbose_name':'Données agro','verbose_name_plural':'Données agro'},
        ),

        # ── SerieAnnuelle ─────────────────────────────────────────────────────
        migrations.CreateModel(
            name='SerieAnnuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('station', models.ForeignKey('Station',
                    on_delete=django.db.models.deletion.CASCADE, related_name='series')),
                ('parametre', models.CharField(max_length=10,
                    choices=[('RRR','Précipitation (mm)'),('fff','Vent total'),('fdfdfd','Vent diurne'),
                             ('Tn','Température min (°C)'),('Tx','Température max (°C)'),
                             ('Un','Humidité min (%)'),('Ux','Humidité max (%)'),
                             ('Id','Insolation (h)'),('Ev','Évaporation (mm)'),
                             ('Tng','T° sol 10 cm (°C)')],
                    verbose_name='Paramètre')),
                ('annee', models.IntegerField(verbose_name='Année')),
                ('nom',  models.CharField(max_length=100, blank=True)),
                ('longitude', models.FloatField(null=True, blank=True)),
                ('latitude',  models.FloatField(null=True, blank=True)),
                ('altitude',  models.FloatField(null=True, blank=True)),
                # 36 colonnes décadaires : d{1|2|3}{Janv|Fev|Mars|Avr|Mai|Juin|Jul|Aout|Sept|Oct|Nov|Dec}
                ('d1Janv',models.FloatField(null=True,blank=True)),('d2Janv',models.FloatField(null=True,blank=True)),('d3Janv',models.FloatField(null=True,blank=True)),
                ('d1Fev', models.FloatField(null=True,blank=True)),('d2Fev', models.FloatField(null=True,blank=True)),('d3Fev', models.FloatField(null=True,blank=True)),
                ('d1Mars',models.FloatField(null=True,blank=True)),('d2Mars',models.FloatField(null=True,blank=True)),('d3Mars',models.FloatField(null=True,blank=True)),
                ('d1Avr', models.FloatField(null=True,blank=True)),('d2Avr', models.FloatField(null=True,blank=True)),('d3Avr', models.FloatField(null=True,blank=True)),
                ('d1Mai', models.FloatField(null=True,blank=True)),('d2Mai', models.FloatField(null=True,blank=True)),('d3Mai', models.FloatField(null=True,blank=True)),
                ('d1Juin',models.FloatField(null=True,blank=True)),('d2Juin',models.FloatField(null=True,blank=True)),('d3Juin',models.FloatField(null=True,blank=True)),
                ('d1Jul', models.FloatField(null=True,blank=True)),('d2Jul', models.FloatField(null=True,blank=True)),('d3Jul', models.FloatField(null=True,blank=True)),
                ('d1Aout',models.FloatField(null=True,blank=True)),('d2Aout',models.FloatField(null=True,blank=True)),('d3Aout',models.FloatField(null=True,blank=True)),
                ('d1Sept',models.FloatField(null=True,blank=True)),('d2Sept',models.FloatField(null=True,blank=True)),('d3Sept',models.FloatField(null=True,blank=True)),
                ('d1Oct', models.FloatField(null=True,blank=True)),('d2Oct', models.FloatField(null=True,blank=True)),('d3Oct', models.FloatField(null=True,blank=True)),
                ('d1Nov', models.FloatField(null=True,blank=True)),('d2Nov', models.FloatField(null=True,blank=True)),('d3Nov', models.FloatField(null=True,blank=True)),
                ('d1Dec', models.FloatField(null=True,blank=True)),('d2Dec', models.FloatField(null=True,blank=True)),('d3Dec', models.FloatField(null=True,blank=True)),
            ],
            options={'verbose_name':'Série annuelle','verbose_name_plural':'Séries annuelles',
                     'ordering':['station','parametre','-annee']},
        ),
        migrations.AlterUniqueTogether(
            name='serieannuelle',
            unique_together={('station','parametre','annee')},
        ),
    ]
